title:        Bizzby Tech
tagline:      "Bizzby's tech blog"
description:  "Ideas, inspiration, and implementation from the engineering team at Bizzby."
url:          http://tech.bizzby.com
markdown:     kramdown
permalink:    pretty
highlighter:  pygments
paginate:     5
